# Generated by Django 2.2 on 2019-07-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewcrud', '0003_auto_20190724_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_thumbnail_url',
        ),
    ]
