# Generated by Django 2.2 on 2019-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcrud', '0004_remove_comment_comment_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_thumbnail_url',
            field=models.TextField(default='', max_length=300),
        ),
    ]
